changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
      - dependabot[bot]
  categories:
    - title: Added
      labels:
        - enhancement
    - title: Fixed
      labels:
        - bug
    - title: Security
      labels:
        - security
    - title: Documentation
      labels:
        - documentation
    - title: Dependencies
      labels:
        - dependencies
        - github_actions
    - title: Other Changes
      labels:
        - "*"
